name: ${project.name}
main: ${project.groupId}.${project.artifactId}.Main
version: ${project.version}
author: LeonTG77
description: Teams are unknown and will not be displayed to everyone. You can also enable where it will show what team a player is on when they get a kill.
softdepend: [ProtocolLib]

commands:
  secretteams:
    description: Enable or Disable secret teams.
    aliases: [steams]